server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true

spring:
  application:
    name: service-feign

feign:
  hystrix:
    enabled: true